Backend: Vivado
Board: xczu9eg-ffvb1156-2-e
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,9>
    ReuseFactor: 1
    Strategy: resource
IOType: io_stream
InputData: null
KerasModel: !keras_model 'hls_qmodel/imgonly_qmodel_bnfold_4/keras_model.h5'
OutputDir: hls_qmodel/imgonly_qmodel_bnfold_4
OutputPredictions: null
ProjectName: myproject
Stamp: C7E48Ee1
XilinxPart: xcku115-flvb2104-2-i
